---
title: "SLE_Final_Project"
author: "Jessica Salas"
date: "12/3/2018"
output:
  word_document: default
  html_document: default
bibliography: references_SLE_Final_Paper.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(citr)
library(wordcountaddin)
```

# Introduction

 What is an Organoid?

Organoids are stem-cell derived structures that are developed in order to study specific structures in vitro while preserving the physiology of in tact organs. Organoids provide the opportunity for modeling and studying normal development and disease development of specific structures. The use of organoids is heavily relied on for toxicology studies in the pharmaceutical industry as well as overall molecule characterization. 

Organoids are 3D structures that have been demonstrated to properly exhibit key structural and functional properties of different organs. Organoids can be grown from two types of cells: pluripotent stem cells and/ or organ-restricted adult stem cells (aSCs). Pluripotent stem cells are embryonic stem (ES) cells and induced pluripotent stem (iPS) cells [@bredenoord2017human]. The stem cells are driven toward specific lineages through manipulation of growth factors and culture media. By controlling this cell differentiation, researchers can essentially control what organ is modeled [@bredenoord2017human]. A key aspect of organoid development is the 3D support matrix that allows for the correct spatial organization in the organoid. The end product is a completely in vitro model of an organ that correctly resembles the architecture and physiology of a working organ. 

## History of Organoid Development
Organoid development for research purposes has been evolving since the early 1900s. It was in 1906 when researchers were looking for a way to replicate organogenesis- the process of organ development in humans or animals. Ross Harrison, the researcher credited with developing the technique, originally was looking to study the origin of nerve fibers [@simian2017organoids]. To study the nerve fibers he took a small fragment of embryo nerve cord and placed it on a cover slip in the lab. By inverting and sealing the cover slip on the hollow side, Harrison was able to observe adequate nerve growth on the cover slip and conduct his analysis [@simian2017organoids]. Harrison provided a starting point for other researchers looking to conduct similar experiments. Soon after Harrison, a slew of researchers were able to develop better and more efficient techniques to conduct research. By the 1920s, the scope of research shifted from organ development to embryo development and so more research methods were developed as well. Specifically, the development of tube cultures and a method known as "the watch glass method". By the 1950s, researchers had managed to culture other organs in vitro but with the given limitations of the methods used. Some of the limitations include the need for small, thin organ slices and preventing necrosis- the death of most or all cells of a tissue or organ within the sample dish [@simian2017organoids]. Fast forwarding to the 1980s, the research done in the early 1900s allowed for the advancements of 3D organoid development because now researchers had the conceptual and methodical background to focus in on tissue-specific function for in vitro experiments. The evidence of such advancements came in 1992 when researchers working with 3D models of human breast cells and tumor biopsied carcinoma cells were cultured in an in vitro, extracellular matrix that effectively mimicked the disease and verified that the culture system could replicate the growth, structural, and functional differences of these cells [@simian2017organoids]. In the oncology realm, this advancement was critical to begin understanding the epidemiology of breast cancer. 

In 2011, Madeline Lancaster, a cell biologist at the Institute of Molecular Biotechnology of the Austrian Academy of Sciences in Vienna, had been trying to generate 2D neural structures that are derived from embryonic stem cells. At the time Lancaster lacked significant tissue culture experience and so in some dishes the cells did not behaved as expected. Instead of sticking to the plastic surface of the dish, they rolled up into 3D floating objects whit a self- organized structure. Understanding their potential, she began growing and developing these structures until they resembled the human brain tissue. Later in 2013, she published her findings and concluded that the "mini brains" included a cerebral cortex and differentiated neuronal cells [@nowogrodzki2018cerebral]. Much of the process to develop a brain organoid is similar to developing other types of organoids except that each step is highly specialized for neuronal formation. The cerebral organoid successfully modeled the different interdependent regions of the brain as well as mature populations of cortical neuron subtypes [@lancaster2013cerebral]. When analyzed for correct location and phenotypic development, the researchers were pleasantly surprised that the development was consistent with their proposed hypotheses [@lancaster2013cerebral]. 

## Caveats with Cerebral Organoid Research


# Legal Implications
Although greatly impactful for scientists, cerebral organoids and their production could be a slippery slope when considering the legal matters of such usage. Organoid research is closely related to stem cell research when considering their legal implications and for that reason, organoid research has already been very tightly regulated. As of today, organoids are not an option for pre-clinical research as a replacement for the traditional forms of *in vitro* or *in vivo* testing before moving to clinical trials. Some legal issues that have risen with the use of cerebral organoids include the patentability of the organoids made, the regulations for operating within a regulated environment, and the necessary, standardized guidelines for the production and use of cerebral organoids in research settings. 

As with other innovative techniques for drug research and development, necessary measures should be taken to regulate the activity of these new tools. Cerebral organoids are no exception, especially given the biological complexity of the organoid in question. Currently stem cell research is heavily regulated but these regulations do not necessarily cover the specific details to cerebral organoids. There are guidelines in place such as the National Statement on Ethical Conduct in Human Research by the National Health and Medical Research Council which protect donors' privacy when considering stem cell research but there is an obvious gap when considering organoid development. In the specific case of organoid development, there are no specific privacy laws that have been put into place which means that donors (consensual and non-consensual) could be in danger. Organoids are still derived from a human cellular basis which means that the cells originated from an individual whether they know it or not. Proper informed consent is necessary for any type of development of organoids in the future- especially when considering cerebral organoids. The topic of informed consent becomes particularly of interest when considering the use of the organoid produced. Specifically, if any clinical advancements are made using the cerebral organoid developed from a patient, should the patient be informed and/ or compensated? Moreover, another question of consent arises when considering the the future of cerebral organoid development. As extreme as it sounds, there are already implications that scientists will be able to "revive" brains of deceased patients using cerebral organoids. Specifically, scientists are already anticipating the possibility of generating cerebral organoids from deceased patients and tapping into the long-term memory of these patients [@lavazza2018cerebral]. Although outliandish, this possibility brings consent and privacy to a completely different level. 

# Social Implications
The development of cerebral organoids can greatly contribute to the research currently being conducted for the cure of neurological disease and disorders. Research in the neuroscience field is by no means lagging, but what is lagging is a viable way to test new therapeutics to ensure their approval by the FDA. To put it in perspective, there are no drugs or treatments currently approved for neurodegenerative disease on the market today in 2018 [@hung2017drug]. With that said, there are many treatments for the **symptoms** of neurodegenerative diseases but none of these drugs treat the underlying pathology of the diseases.

In terms of disease replication- cerebral organoids would be a better alternative to other types of *in vivo* research because the cerebral organoid would better model the disease than in given animal models given that the organoid would mimic the appearance and limited activity of human patients. For example, in microcephaly, a disease characterized by the substantial reduction in brain size, it is very difficult for researchers to study the disease pathology in small organisms such as mice or rats. Another added difficulty is the difference in brain development across model organisms [@brustle2013developmental]. The same principle is true for other neurological diseases that develop over a longer period of time like dimentias.

In the research being done today, drugs that are developed are first tested *in vitro* in cellular assays before moving on to extensive *in vivo* testing in animals. Having worked firsthand in the industry, the tremendous amount of animal testing that is conducted is quite upsetting. What is even more upsetting is the fact that the animal studies that are conducted are mostly arbitrary to the end result of the drug's activity because the cerebral systems are so different from those of humans. In 2009, 1,131,076 animals were tested on for pharmaceutical purposes. The result was 19 newly approved therapies by the FDA- a typical approval rate for a given year [@hughes20102009]. The typical timeline for neurological drug testing is similar to that of other types of drugs but with a much lower, almost nonexistent, approval track record. The cause of such negative clinical trials could be contributed to a variety of factors but the most important one being the lack of viable testing. Testing these neurological drugs on rodents and later on in monkeys is costly and relatively slow to what could be tested on using cerebral organoids. Although it does take time to generate the organoid in the lab, the turn around time could be much quicker and without the need of essentially blindly testing on unrelated organisms. 

Cerebral organoids can positively contribute to the production of drugs to treat neurological disorders in other important aspect as well- cost. It is no secret the cost to produce a drug that is FDA- approved is extremely expensive. In fact, the average cost to produce a drug today is \$2.6B. This figure is up from \$802M in 2003 [@moore2018estimated]. This figure represents the average cost of preclinical and clinical research and development required for producing **one** drug. If there is a way we could reduce the cost to companies, organoids could be a viable option. Since cerebral organoids would essentially mimic the brains of patients and healthy subjects, maybe this could contribute to smaller clinical trial groups and therefore, a lower development cost overall. Taking a step back, cerebral organoid could be done in the early stages of pre-clinical research as a replacement for animal studies to reduce costs at this stage as well. 

The use of cerebral organoids is not only confined to the pre-clinical aspect of treatment development- it could prove to be a viable treatment option itself. Since the brain is a highly specialized with a very specific 3D structure that must be maintained, cerebral organoids could provide the patient with an exact match of specific structures that could be replaced [@lavazza2018cerebral]. Looking to the future, the use of cerebral organoid usage should be considered to support the ongoing research for finding cures to neurological diseases. 

# Ethical Implications
Although the need for cerebral organoids is critical to the advancement of research for neurological diseases, there are several ethical topics that need to be considered as we are progressing forward. Similar to the ethical debates surrounding stem cell research and usage, these issues are at the forefront of cerebral organoid research as well- the use of embryonic stem cells, the donor consent, the storage and use of such organoids, and the transparency with patients regarding any clinically relevant findings [@lavazza2018cerebral]. Additional ethical issues regarding cerebral organoids include the possible creation of life, the acquisition of human qualities, and finally what should be done in the event that such structures develop consciousness and defining consciousness. Using the ethical theories listed below, I will aim to provide details for for what has been done or what should be done in each given case. 

Although consciousness has not yet been detected in the cerebral models, scientists have shown that there are surges of electrical activity that could be detected and therefore could prove to be conscious-like signs [@lavazza2018cerebral]. Evaluating consciousness is an issue that must be approached very carefully because the definition of consciousness could provide the basis for any legal decisions made regarding cerebral organoids in the future. When considering the aspect of consciousness, there needs to be a distinction made between an nonhuman research organism and a human being. Currently there is no evidence that cerebral organoids can mature to be sentient- able to experience pain sensation, but looking forward to the future, it is in all likely that organoids can be developed to acquire sensory and cognitive functions alike [@lavazza2018cerebral]. 

## Cultural Relativism
As mentioned above, there is a great need for developing new ways to study diseases- specifically neurological diseases. Cerebral organoids could provide a the missing piece necessary to model diseases and treat them accordingly. As the theory of Cultural Relativism is defined as "Right and wrong rests with the society's moral guidelines", it is important to consider the society at hand. Generally speaking, the Western Society is much more open to new types of research especially in the realm of medical research. Looking through the lens of Cultural Relativism, it is clear why the science community is actively pursuing the advancement of such technology. Experimentation is the basis for innovation and these innovations are extremely important when looking at new ways to treat diseases. 

The downside to the possible generation and use of cerebral organoids is worrysome to think about because the overall goals of the researchers conducting studies might not be clearly defined. A relevant example that we covered in class is when Apple donated laptops to under-served schools with the intention that they would become Apple customers in the future. Similar to the Apple employees in this case, scientists could have different intentions. Let's say that a cerebral organoid is produced from a a patient with the understanding that it will be used to study the patient's disease status. While developing this organoid, researchers use the organoid to model other forms of the disease and gather the data for studies in the future. Furthermore, scientists could be generating these organoids for personal gain and not solely to contribute to biomedical research. 

## Ethical Egoism
In the scope of Ethical Egoism, an action is considered good if it benefits your neighbor but does not negatively harm you in the process. This can be summarized not as the "Golden Rule", but instead as the "Silver Rule". According to the "Silver Rule", it is better to let people take care of themselves because essentially, everyone knows what is best for themselves but not for others. Through the lens of ethical egoism, it is morally right that scientists and researchers can perform the necessary research because that is what is best for the individuals conducting the studies. The ethical egoism lens does not take into consideration what is best for the patients involved in the study and their well-being. This highlights an important caveat of ethical egoism and for this reason there are many people who see cerebral organoid research as a threatening development. Since ethical egoism promotes more of a "Me first" attitude, many people outside of the research realm could see this as an area of potential debate in the future. 
## Virtue Ethics

You can also embed plots, for example:

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
